language: node_js

node_js:
- node

script: yarn && yarn test && yarn build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn semantic-release

cache: yarn

notifications:
  email: false
